# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_choice',
            field=models.CharField(choices=[('E', 'English'), ('M', 'Medium'), ('B', 'Bangla')], default='null', max_length=1),
        ),
    ]
